@startuml Manage Section (PUT)

header Online Job Fair Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Section (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:sections" as routerSections
participant "<<middleware>>\n:auth" as middleAuth
participant "<<controllers>>\n:sections" as controllersSections
participant "<<model>>\n:Section" as modelSection
database "<<MongoDB>>\n:sections" as SectionsDatabase

client -> server ++: req.put('/sections/:id')
server -> routerSections ++: app.use('/sections', sections)
routerSections -> middleAuth ++: protect(), authorize('admin')
middleAuth -> controllersSections ++: updateSections()
controllersSections -> modelSection ++: findByIdAndUpdate(req.params.id, req.body)
modelSection -> SectionsDatabase ++: SectionSchema
SectionsDatabase --> modelSection --: section
controllersSections <-- modelSection --: section
controllersSections -> client --: response

@enduml